[package]
name = "kiss"
version = "0.1.0"
edition = "2021"

[dependencies]
libc = "0.2"
crossbeam-channel = "0.5"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
strip = true